---
- name: Copy docker config files to hosts
  copy:
    src: "{{item.file}}"
    dest: "{{item.path}}"
    backup: no
  register: copy_docker_files
  with_items:
    - file: daemon.json
      path: /etc/docker/
    - file: taskmax.conf
      path: /etc/systemd/system/docker.service.d/
  tags:
    - config
    - docker
    - file

- name: Restart Docker & Daemon
  when: copy_docker_files.changed
  systemd:
    state: restarted
    name: docker
    daemon_reload: yes
    force: yes
    enabled: yes
