---
- name: Copy docker config files to hosts
  copy:
    src: "{{item.file}}"
    dest: "{{item.path}}"
    backup: no
  register: copy_docker_files
  with_items:
    - file: daemon.json
      path: /etc/docker/
    - file: taskmax.conf
      path: /etc/systemd/system/docker.service.d/
  notify:
    - Restart Docker & Daemon
  tags:
    - config
    - docker
    - file
