---
- name: Gather facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['haproxy'] }}"

- name: Copy calicoctl.cfg
  copy:
    src: "calicoctl.cfg"
    dest: "/etc/calico/"
    backup: no

- name: Copy calico-bgpconfiguration.yml
  template:
    src: calico-bgpconfiguration.yml.j2
    dest: $HOME/calico-bgpconfiguration.yml
    backup: no

- name: Copy calico-installation.yml
  template:
    src: calico-installation.yml.j2
    dest: $HOME/calico-installation.yml
    backup: no
