config_files:
  cri_o:
    - file: etc/containers/registries.conf
      path: /etc/containers/
    - file: etc/modules-load.d/k8s.conf
      path: /etc/modules-load.d/
    - file: etc/sysctl.d/k8s.conf
      path: /etc/sysctl.d/
  kubelet:
    - file: etc/kubernetes/kubelet.env
      path: /etc/kubernetes/
  repositories:
    - file: etc/yum.repos.d/kubernetes.repo
      path: /etc/yum.repos.d/
  NetworkManager:
    - file: etc/NetworkManager/conf.d/calico.conf
      path: /etc/NetworkManager/conf.d/
additional_pacman_packages:
  - kubectl
  - kubeadm
  - kubelet
  - python3-pip
  - cri-o
additional_python_packages:
  - PyYAML
kubernetes_version: 1.24
