---
- name: Check if Tigera-Operator namespace exists
  register: tigera_namespace
  failed_when: false
  shell: kubectl get pods  --namespace=tigera-operator | awk '{ print $1}' | grep tigera

- name: Deploy Tigera-Operator Network
  when: tigera_namespace.stdout == ""
  shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

- name: Copy calico templates
  register: calico_installation
  template:
    src: calico-installation.yml.j2
    dest: $HOME/calico-installation.yml
    backup: no

- name: Deploy calico-installation.yml
  when: calico_installation.changed
  shell: kubectl apply -f $HOME/calico-installation.yml

- name: Copy calico templates
  register: calico_bgpconfiguration
  template:
    src: calico-bgpconfiguration.yml.j2
    dest: $HOME/calico-bgpconfiguration.yml
    backup: no

- name: Apply calico-bgpconfiguration.yml
  when: calico_bgpconfiguration.changed
  shell: calicoctl apply -f $HOME/calico-bgpconfiguration.yml
