---
- name: Deploy the Tigera Operator
  shell: kubectl apply -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

- name: Install calico-installation-crd.yml.j2 -> $HOME/calico-installation-crd.yml
  template:
    src: calico-installation-crd.yml.j2
    dest: $HOME/calico-installation-crd.yml
    backup: no

- name: Deploy Calico Pod Network
  shell: kubectl apply -f $HOME/calico-installation-crd.yml
