---
- name: Deploy Tigera-Operator Network
  shell: kubectl apply -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

- name: Copy calico CRD
  template:
    src: custom-resources.yml.j2
    dest: $HOME/custom-resources.yml
    backup: no

- name: Deploy calico-system
  shell: kubectl apply -f $HOME/custom-resources.yml
