---
- name: Create Tigera-Operator Network
  shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

- name: Deploy calico-installation.yml
  shell: kubectl apply -f $HOME/calico-installation.yml

- name: Apply calico-bgpconfiguration.yml
  shell: calicoctl apply -f $HOME/calico-bgpconfiguration.yml
