---
- name: ensure all hosts know about each other
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: no

# TODO: move to own role
# - name: Test all hosts know about each other
#   include_tasks: test_connectivity.yml
#   loop: "{{groups['datacenter']}}"
