---
- name: ensure all hosts know about each other
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: no

- name: Restart systemd-resolved
  systemd:
    state: restarted
    name: systemd-resolved
- name: Restart systemd-networkd
  systemd:
    state: restarted
    name: systemd-networkd

- name: Test all hosts know about each other
  include_tasks: test_connectivity.yml
  loop: "{{groups['datacenter']}}"
