---
- name: Test All hosts know about "{{hostvars[item]['inventory_hostname_short'] }}"
  shell: cat /etc/hosts | grep {{hostvars[item]['inventory_hostname_short']  }}
  register: hosts_grep

- name: Assert that "{{hostvars[item]['inventory_hostname_short'] }}" knows about itself
  assert:
    that: "'127.0.1.1' in hosts_grep.stdout"
    quiet: true
  when: inventory_hostname_short == hostvars[item]['inventory_hostname_short']

- name: Assert that all hosts know about "{{hostvars[item]['inventory_hostname_short'] }}"
  assert:
    that: "'{{hostvars[item]['ansible_eth0']['ipv4']['address']}}' in hosts_grep.stdout"
    quiet: true
  when: inventory_hostname_short != hostvars[item]['inventory_hostname_short']
