---
- name: Install additional packages
  import_tasks: install_additional_dependencies.yml
- name: Install Python modules
  import_tasks: install_python_modules.yml
- name: Restart docker
  systemd:
    state: restarted
    name: docker
    daemon_reload: yes
    force: yes
    enabled: yes
