---
- block:
    - import_tasks: helm_ingress_nginx.yml
    - import_tasks: define_ingress_controller.yml
  when: inventory_hostname is in groups['leader']

- import_tasks: register_controller_nodeport_with_haproxy.yml
