---
- hosts: datacenter
  roles:
    - hosts_file

- hosts: registry
  roles:
    - docker_registry

- hosts: loadbalancer
  roles:
    - haproxy

- hosts: cluster
  any_errors_fatal: true
  roles:
    - prerequisites

- hosts: leader
  any_errors_fatal: true
  roles:
    - helm_config

- hosts: cluster
  any_errors_fatal: true
  roles:
    - k8s

- hosts: leader:loadbalancer
  any_errors_fatal: true
  roles:
    - ingress_controller

- hosts: leader
  any_errors_fatal: true
  roles:
    - cert_manager
    - dashboard
