---
- hosts: datacenter
  roles:
    - hosts_file

- hosts: haproxy_group
  roles:
    - haproxy

- hosts: cluster
  roles:
    # - configure_cluster_dns
    - cluster

- hosts: leader
  roles:
    - test_dns
