---
- hosts: datacenter
  roles:
    - hosts_file

- hosts: haproxy_group
  roles:
    - haproxy

- hosts: cluster
  any_errors_fatal: true
  roles:
    - prerequisites
    - k8s

- hosts: leader
  any_errors_fatal: true
  roles:
    - test_dns
    - dashboard
