---
- name: kubectl exec -ti dnsutils -- nslookup kubernetes.default
  shell: kubectl exec -ti dnsutils -- nslookup kubernetes.default
  register: nslookup_out

- name: assert equal
  assert:
    that:
      - nslookup_out.stderr | length == 0
      - '"10.96.0.10#53" in nslookup_out.stdout'
      - '"kubernetes.default.svc.cluster.local" in nslookup_out.stdout'
