version: "3.3"
networks:
  mongo:
    external: true
  mongos:
    external: true

services:
  d-01:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
    volumes:
      - /data/db-01:/data/db
    command: mongod --shardsvr --replSet datars --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  d-02:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
    volumes:
      - /data/db-02:/data/db
    command: mongod --shardsvr --replSet datars --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  d-03:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
    volumes:
      - /data/db-03:/data/db
    command: mongod --shardsvr --replSet datars --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  c-01:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
    volumes:
      - /data/config-01:/data/db
    command: mongod --configsvr --replSet configrs --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  c-02:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
    volumes:
      - /data/config-02:/data/db
    command: mongod --configsvr --replSet configrs --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  c-03:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
    volumes:
      - /data/config-03:/data/db
    command: mongod --configsvr --replSet configrs --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  q-01:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
      - mongos
    ports:
      - "27117:27017"
    command: mongos --configdb configrs/c-01:27017,c-02:27017,c-03:27017 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  q-02:
    image: 127.0.0.0:5000/mongo:5.0.7-focal
    networks:
      - mongo
      - mongos
    ports:
      - "27217:27017"
    command: mongos --configdb configrs/c-01:27017,c-02:27017,c-03:27017 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1

  s-extraction:
    image: 127.0.0.0:5000/stellarust-extraction-service:latest
    networks:
      - mongos
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1

  s-parsing:
    image: 127.0.0.0:5000/stellarust-parsing-service:latest
    networks:
      - mongos
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1

  s-unzipping:
    image: 127.0.0.0:5000/stellarust-unzipping-service:latest
    networks:
      - mongos
    ports:
      - "8002:8002"
    deploy:
      mode: replicated
      replicas: 1

  s-frontend:
    image: 127.0.0.0:5000/stellarust-frontend-service:latest
    networks:
      - mongos
    ports:
      - "8081:8080"
    deploy:
      mode: replicated
      replicas: 1
