---
- name: Make $HOME/.kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: "0755"

- name: Copy /etc/kubernetes/admin.conf on the remote machine to $HOME/.kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
