---
- name: Copy Configs
  block:
    - import_tasks: copy_configs/copy_docker_configs.yml
    - block:
        - import_tasks: copy_configs/copy_dashboard_configs.yml
        - import_tasks: copy_configs/copy_calico_configs.yml
      when: inventory_hostname == groups['control_plane'][0]
