---
- name: Install Dependencies
  block:
    - name: Install Pacman Dependencies
      pacman:
        name: "{{ additional_pacman_packages }}"
        state: present

    - name: Install kublet
      shell: "pacman -Sdd --nodeps --noconfirm --needed kubelet"

    - name: Install Python Dependencies
      when: additional_python_packages | length > 0
      pip:
        name: "{{ additional_python_packages }}"
        state: present
