---
- name: Launch Cluster
  block:
    - name: create directory /etc/kubernetes
      shell: mkdir -p /etc/kubernetes

    - name: install kubelet.env -> /etc/kubernetes/kubelet.env
      copy:
        src: kubelet.env
        dest: /etc/kubernetes/kubelet.env
        backup: no

    - block:
        - import_tasks: launch_cluster/kubeadm_init_cluster.yml
        - import_tasks: launch_cluster/deploy_pod_network.yml
      when: inventory_hostname == groups['control_plane'][0]

    - import_tasks: launch_cluster/join_control_plane_nodes.yml
      when: inventory_hostname is in groups['control_plane']

    - import_tasks: launch_cluster/join_worker_nodes.yml
      when: inventory_hostname is in groups['cluster']

    - name: "Verify ClusterDNS is actually working, otherwise it will cause many things to silently fail"
      block:
        - import_tasks: launch_cluster/deploy_dnsutils_pod.yml
        - import_tasks: launch_cluster/wait_for_cluster_to_settle.yml
        - import_tasks: launch_cluster/verify_dns.yml
      when: inventory_hostname == groups['control_plane'][0]
