---
- name: Launch Cluster
  block:
    - name: install kubelet.env -> /etc/kubernetes/kubelet.env
      copy:
        src: kubelet.env
        dest: /etc/kubernetes/kubelet.env
        backup: no

    - block:
        - import_tasks: launch_cluster/kubeadm_init_cluster.yml
        - import_tasks: launch_cluster/deploy_pod_network.yml
      when: inventory_hostname == groups['control_plane'][0]

    - import_tasks: launch_cluster/join_control_plane_nodes.yml
      when: inventory_hostname is in groups['control_plane']

    - import_tasks: launch_cluster/join_worker_nodes.yml
      when: inventory_hostname is in groups['cluster']
