---
- name: Install Calico CRDs
  template:
    src: "{{item}}"
    dest: "$HOME/{{item}}"
    backup: no
  with_items:
    - calico_base.yml
    - calico_api.yml

- name: Deploy tigera-operator chart
  kubernetes.core.helm:
    name: calico
    chart_ref: tigera-operator
    chart_repo_url: https://projectcalico.docs.tigera.io/charts
    chart_version: v3.23.1
    release_namespace: tigera-operator
    create_namespace: yes
    values_files:
      - calico_base.yml
      - calico_api.yml
