---
- name: Verify kubernetes is running on localhost
  shell: "curl https://localhost:{{kubernetes_api_port}}"
  failed_when: no
  changed_when: "'curl: (7)' in curl_k8s_leader.stderr"
  tags:
    - bootstrap
    - cluster
  register: curl_k8s_leader

- name: Run Kubeadm Init
  shell: "kubeadm init \
    --pod-network-cidr={{pod_network_cidr}} \
    --control-plane-endpoint haproxy.{{domain}}:{{kubernetes_api_port}} \
    --upload-certs \
    --v 1"
  when: curl_k8s_leader.changed

- name: Make .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0600

- name: Copy /etc/kubernetes/admin.conf on the remote machine to $HOME/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    mode: 0600
    remote_src: yes
