---
- name: Mongo Swarm - Adding Docker Node lables for Mongo instances
  docker_node:
    hostname: "{{hostvars[item]['inventory_hostname_short'] }}"
    labels:
      mongo.replica: "true"
  with_items: "{{ groups['swarm_workers'] }}"
  tags:
    - node
    - docker

- name: Mongo Swarm - Adding Docker Node lables for App instances
  docker_node:
    hostname: "{{ hostvars[item]['inventory_hostname_short'] }}"
    labels:
      app.replica: "true"
  with_items: "{{ groups['swarm_workers'][0:2] }}"
  tags:
    - node
    - docker
