---
- name: Install HAProxy
  import_tasks: install_haproxy.yml
  when: inventory_hostname in groups['haproxy']

- name: HAProxy Config
  import_tasks: haproxy_config.yml
  when: inventory_hostname in groups['haproxy']
