---
- name: Gather facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['control_plane'] }}"

- name: Install HAProxy
  dnf:
    name: haproxy
    state: present

- name: Copy HAProxy Config to point at the master nodes
  register: config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: no

- name: Tell SELinux to allow haproxy to connect by setting haproxy_connect_any=1
  shell: setsebool -P haproxy_connect_any=1

- name: Start HAProxy
  when: config.changed
  systemd:
    state: restarted
    name: haproxy
    enabled: yes

- name: Test that haproxy is active
  include_tasks: test_haproxy_stats.yml
