---
- name: Gather facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['control_plane'] }}"

- name: Install HAProxy
  pacman:
    name: haproxy
    state: present

- name: Copy HAProxy Config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: no
  notify:
    - Start HAProxy

- name: Test that haproxy is active
  include_tasks: test_haproxy_stats.yml
