---
- name: Gather facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['control_plane'] }}"

- name: Install HAProxy
  dnf:
    name: haproxy
    state: present

- name: Expose ports
  block:
    - name: Expose port 6443 and 443
      shell: >
        firewall-cmd --permanent --add-port 6443/tcp;
        firewall-cmd --permanent --add-port 443/tcp;
        firewall-cmd --reload;

- name: Copy HAProxy Config and Point the proxy at the master nodes
  register: config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: no

- name: Tell SELinux to allow haproxy to connect by setting haproxy_connect_any=true
  shell: setsebool -P haproxy_connect_any=1

- name: Start HAProxy
  when: config.changed
  systemd:
    state: restarted
    name: haproxy
    enabled: yes

- name: Test that haproxy is active
  include_tasks: test_haproxy_stats.yml
