---
# see issue here: https://wiki.archlinux.org/title/CRI-O#Configuration

- name: Install CRI-o files
  ansible.builtin.copy:
    src: 00-plugin-dir.conf
    dest: /etc/crio/crio.conf.d/
    backup: no

- name: Install CRI-o files
  ansible.builtin.template:
    src: registries.conf
    dest: /etc/containers/registries.conf
    backup: no

- name: Delete files in /etc/cni/net.d/
  ansible.builtin.file:
    path: "/etc/cni/net.d/{{item}}"
    state: absent
  with_items:
    - 100-crio-bridge.conf
    - 199-crio-loopback.conf

- name: Execute modprobe overlay, br_netfilter
  community.general.modprobe:
    name: "{{item}}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Set values so CRI-o can be used, i don't know what this does
  ansible.posix.sysctl:
    name: "{{item}}"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: start_crio
  systemd:
    state: started
    name: crio
    enabled: yes
