---
- name: create directory /etc/kubernetes
  shell: mkdir -p /etc/kubernetes

- name: install kubelet.env -> /etc/kubernetes/kubelet.env
  copy:
    src: "{{item.file}}"
    dest: "{{item.path}}"
    backup: no
  with_items: "{{config_files.kubelet}}"

- name: enable_kubelet
  systemd:
    name: kubelet
    enabled: yes
