---
- name: Install docker files
  copy:
    src: "{{item.file}}"
    dest: "{{item.path}}"
    backup: no
  register: docker_files
  with_items: "{{config_files.docker}}"

- name: restart_docker_and_daemon
  when: docker_files.changed
  systemd:
    state: restarted
    name: docker
    daemon_reload: yes
    force: yes
    enabled: yes
