---
- name: check if /swap/swapfile exists
  ansible.builtin.stat:
    path: /swap/swapfile
  register: swap_file

- name: Disable Swap
  when: swap_file.stat.exists
  block:
    - name: Turn Off Swap
      ansible.builtin.shell: swapoff /swap/swapfile

    - name: Delete Swapfile
      ansible.builtin.file:
        path: /swap/swapfile
        state: absent

    - name: Remove Swap from /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '(\s+)/swap/swapfile none swap defaults 0 0(\s+.*)?$'
        replace: '\1\2'
        backup: no
