---
- name: Install Dependencies
  block:
    - name: Install dnf packages
      dnf:
        name: "{{ additional_pacman_packages }}"
        disable_excludes: kubernetes
        state: present

    - name: Install pip packages
      when: additional_python_packages | length > 0
      pip:
        name: "{{ additional_python_packages }}"
        state: present
