---
- name: Install Dependencies
  block:
    - name: Install iptables-nft
      shell: "yes | sudo pacman -S iptables-nft --needed"
      register: install_iptables
      changed_when: "'skipping' not in install_iptables.stderr"

    - name: Install Pacman Dependencies
      pacman:
        name: "{{ additional_pacman_packages }}"
        state: present

    - name: Install Python Dependencies
      when: additional_python_packages | length > 0
      pip:
        name: "{{ additional_python_packages }}"
        state: present
