---
- name: "Initial Setup"
  hosts: all
  become: true
  handlers:
    - name: Run mkinitcpio
      shell: mkinitcpio -p linux
    - name: Restart systemd-resolved
      systemd:
        state: restarted
        name: systemd-resolved
    - name: Restart systemd-networkd
      systemd:
        state: restarted
        name: systemd-networkd
  tasks:
    - name: "Append host:~/.ssh/id_rsa.pub to box:~/.ssh/authorized_keys"
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/michael/.ssh/id_rsa.pub') }}"

    - name: Update and upgrade system
      dnf:
        name: "*"
        state: latest
        update_cache: yes
