---
- name: "Initial Setup"
  hosts: all
  become: true
  handlers:
    - name: Run mkinitcpio
      shell: mkinitcpio -p linux
    - name: Restart systemd-resolved
      systemd:
        state: restarted
        name: systemd-resolved
    - name: Restart systemd-networkd
      systemd:
        state: restarted
        name: systemd-networkd
  tasks:
    - name: "Append host:~/.ssh/id_rsa.pub to box:~/.ssh/authorized_keys"
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/michael/.ssh/id_rsa.pub') }}"

    # - name: check if /swap/swapfile exists
    #   stat:
    #     path: /swap/swapfile
    #   register: swap_file

    # - name: Disable Swap
    #   when: swap_file.stat.exists
    #   block:
    #     - name: Turn Off Swap
    #       shell: swapoff /swap/swapfile

    #     - name: Delete Swapfile
    #       shell: rm -f /swap/swapfile

    #     - name: Remove Swap from /etc/fstab
    #       replace:
    #         path: /etc/fstab
    #         regexp: '(\s+)/swap/swapfile none swap defaults 0 0(\s+.*)?$'
    #         replace: '\1\2'
    #         backup: no

    - name: Update modules with virtio drivers
      replace:
        path: /etc/mkinitcpio.conf
        regexp: '(\s+)MODULES=\(\)(\s+.*)?$'
        replace: '\1MODULES=(virtio virtio_pci virtio_blk virtio_net virtio_ring)\2'
        backup: no
      notify: Run mkinitcpio

    - name: Attach datacenter.local DNS to network interface eth1
      lineinfile:
        path: /etc/systemd/network/eth1.network
        search_string: "Domains=datacenter.local"
        line: "Domains=datacenter.local ~local"
        insertafter: "DHCP=ipv4"
        backup: no
      notify:
        - Restart systemd-networkd

    - name: use global DNS
      replace:
        path: /etc/systemd/resolved.conf
        regexp: '(\s+)#DNS=(\s+.*)?$'
        replace: '\1DNS=1.1.1.1 1.0.0.1\2'
        backup: no
      notify:
        - Restart systemd-resolved
