---
- name: "Initial Setup"
  hosts: all
  become: true
  handlers:
    - name: Run mkinitcpio
      shell: mkinitcpio -p linux
    - name: Restart systemd-resolved
      systemd:
        state: restarted
        name: systemd-resolved
    - name: Restart systemd-networkd
      systemd:
        state: restarted
        name: systemd-networkd
  tasks:
    - name: "Append host:~/.ssh/id_rsa.pub to box:~/.ssh/authorized_keys"
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/michael/.ssh/id_rsa.pub') }}"

    - name: Cleanup old registration since it's broken now
      shell: subscription-manager clean

    - name: Register System or Red Hat will Take away your repositories
      shell: subscription-manager register --username YOUR_USER_NAME --password ************************** --auto-attach
