Vagrant.configure("2") do |config|

    config.vm.box = "archlinux/archlinux"
    config.ssh.forward_agent = true
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.cache.scope = :machine
    config.cache.auto_detect = false
    config.cache.enable :pacman
    config.cache.enable :pip  
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['nfsvers=4 || mount -o rw', 'vers=4']

    }

    config.vm.provider "libvirt" do |lv|
      lv.memory = (32*1024)
      lv.cpus = 32
      lv.nested = true
			lv.default_prefix = "stellarustCluster_"
      lv.disk_bus = "virtio"
      lv.disk_driver :cache => "writeback"
      lv.nic_model_type = "virtio"
      lv.driver = "kvm"
      lv.video_type = "virtio"
    end

    config.vm.network "private_network", 
      :dev => "virbr1", 
      :mode => "bridge", 
      :type => "dhcp", 
      :libvirt__domain_name => "stellarust.com",
      :libvirt__network_name => "stellarust.com",
      :libvirt__network_address => "10.11.0.0/24"


    define_datacenter config,2,2

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "config.yml"
    end

end

def define_datacenter(config, n_control_plane, n_worker)
  define_haproxy config
  define_k8s config,n_control_plane, n_worker
end

def define_haproxy(config)
  name = "haproxy"
  config.vm.define name do |proxy|
    proxy.vm.hostname = name 
    [8001, 6443].each do |port|
      proxy.vm.network "forwarded_port", guest: port, host: port
    end
  end
end

def define_k8s(config, n_control_plane, n_worker)
  define_control_plane config, n_control_plane
  define_worker_plane config, n_worker
end

def define_control_plane(config, n_control_plane)
  (1..n_control_plane).each do |i|
    define_master config,i
  end
end

def define_master(config, number)
  name = "master-#{number.to_s.rjust(2, "0")}"
  config.vm.define name do |node| 
    node.vm.hostname = name
  end
end

def define_worker_plane(config, n_worker)
  (1..n_worker).each do |i| 
    define_worker config, i
  end
end

def define_worker(config, number) 
  name = "worker-#{number.to_s.rjust(2, "0")}"
  config.vm.define name  do |node| 
    node.vm.hostname = name
  end 
end
