- name: "Copy {{docker_hub_images + docker_stellarust_images}} to primary Manager"
  copy:
    src: "{{item[0]}}.{{item[1]}}"
    dest: /tmp/
  when: inventory_hostname == groups['swarm_managers'][0]
  with_nested:
    - "{{docker_hub_images + docker_stellarust_images}}"
    - ["tar.xz", "sha256"]
  tags:
    - images
    - docker
