---
- name: Configure systemd-resolved to use kube-dns ip as dns server
  replace:
    path: /etc/systemd/resolved.conf
    regexp: "#DNS="
    replace: "DNS=10.96.0.10 8.8.8.8"
  tags: [DNS, systemd-resolved]

- name: iptables
  shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  tags: [nslookup, iptables]

- name: restart_systemd_resolved
  systemd:
    name: systemd-resolved
    state: restarted
    force: yes
  tags: [systemd-resolved]
