---
- name: Ensure docker dir exists
  file:
    path: /etc/docker/
    state: directory

- name: Copy docker config files to host
  register: docker_config
  template:
    src: daemon.json
    dest: /etc/docker/
    backup: no

- name: Install docker
  pacman:
    name: docker
    state: present

- name: Install docker[tls]
  pip:
    name: docker[tls]
    state: present

- name: Restart docker
  when: docker_config.changed
  systemd:
    state: restarted
    name: docker
    daemon_reload: yes
    force: yes
    enabled: yes

- name: Start the registry container on the host network because otherwise it doesn't work
  community.docker.docker_container:
    name: registry
    image: registry:2
    state: started
    network_mode: host
    env:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
