---
- name: Define Issuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{cluster_issuer_name}}"
      spec:
        selfSigned: {}
