---
- name: Install Cert Manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: cert-manager
    chart_repo_url: https://charts.jetstack.io
    release_namespace: cert-manager
    chart_version: "{{cert_manager_version}}"
    create_namespace: yes
    values:
      installCRDs: true
